# Generated by Django 6.0 on 2026-01-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
